---
name: reviewdog

on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: detect-secrets
      uses: ./
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        workdir: testdata
